version: 2.1

workflows:
  all-tests:
    jobs:
    - test:
        matrix:
          parameters:
            python-version: ["3.10", "3.11", "3.12"]

commands:
  save-worker-test-results:
    steps:
      - store_test_results: # report the test results (in test-results/junit.xml) to CircleCI
          path: /workspace/test-results

jobs:
  test:
    parameters:
      python-version:
        type: string

    docker:
    - image: cimg/python:<< parameters.python-version >>
    resource_class: small
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          pip install -e '.[farconf-dev]'
    # Run the most informative steps first, even if they're longer
    - run:
        name: Tests
        command: |
          pytest --junitxml=test-results/junit.xml --cov --cov-fail-under=100 --cov-report=xml
    - save-worker-test-results
    - run:
        name: Check types
        command: |
          pyright .
    - run:
        name: Lint
        command: |
          ruff .
    - run:
        name: Check formatting
        command: |
          ruff format --diff .
